#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
#alias \
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	#ls='lsd -Fla' \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkdir="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ccat="highlight --out-format=ansi" \
	diff="diff --color=auto" \
	grep="grep --color=auto" \
	ip="ip -color=auto"
# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	n="sudo npm" \
	ni="sudo npm install -g" \
	xq="xbps-query" \
	z="zathura"
	#xi="sudo xbps-install" \
	#xr="sudo xbps-remove -R" \
alias \
	g="git" \
	gpush="git push origin master"
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

alias \
	userlist="cut -d: -f1 /etc/passwd | sort" \
	wget="wget -c" \
	myip="curl http://ipecho.net/plain; echo" \
	free="free -m" \
	SS="sudo systemctl" \
	jctl="journalctl -p 3 -xb" \
	emp="cd Documents/Empreses/"
alias \
	calcurse-caldav='CALCURSE_CALDAV_PASSWORD=$(pass show Cloud/calcurse) calcurse-caldav' \
	calcurse="calcurse -D ~/.config/calcurse"

# GIT
alias \
	multipull="find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;" \
	ipe='curl ipinfo.io/ip' \
	hg='history | grep $1' \
	google='ping 8.8.8.8' \
	logs='journalctl -f' \
	gcom='git-commander'
alias \
	check-moon='curl wttr.in/Moon' \
	check-weather='curl wttr.in/Weather'

# Instal·lació
alias \
	paclist="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'" \
	pi="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S" \
	pd="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns" \
	pa="sudo pacman -Syu"
